{% set version = "5.0.0.6" %}

package:
  name: nvcomp
  version: {{ version }}

{% set arm_variant_type = arm_variant_type | default("None") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
source:
  - url: "https://files.pythonhosted.org/packages/e3/b5/1c3b2493dbcd0f436715b3faba4bef4747743dbb1828ce7823e61423863c/nvidia_nvcomp_cu12-5.0.0.6-py3-none-manylinux_2_28_x86_64.whl"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "b5b8a9a3ed33c4a87bb9103fbe59c83b28e4559234447ad40cab11896557c031"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://files.pythonhosted.org/packages/8b/96/530b265e36e23e1e8dd88c864d5479bfd116d9c6cd78c6e3bf91cdf68c62/nvidia_nvcomp_cu12-5.0.0.6-py3-none-manylinux_2_28_aarch64.whl"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "7af1093e866ee7a468753e3df94327fd63ba253dd119a2c04cd18df1761f4754"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://files.pythonhosted.org/packages/cd/96/346d570be6699a49d6347de440d167f0dc9411f6f4fed18ecc2262cec804/nvidia_nvcomp_cu12-5.0.0.6-py3-none-win_amd64.whl"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "8be6bb6d88f17359d44922e19a9cbb3305e6a9030a01f5dd30d1caaea4b45a5a"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]

  - url: "https://files.pythonhosted.org/packages/56/c9/f8a1b957f949ab4c4dc29e7f56316a2224b92c78cad9a66aeab2b36f8857/nvidia_nvcomp_cu13-5.0.0.6-py3-none-manylinux_2_28_x86_64.whl"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "91a4e4b1dc15b0f38e54a3353c917086c99c9f415e1ad79a57d5f28d62b68a4d"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://files.pythonhosted.org/packages/a3/86/e5eccb10e8be41501dfb7191a6b2cff32558d0bba3370ae67f37561caf43/nvidia_nvcomp_cu13-5.0.0.6-py3-none-manylinux_2_28_aarch64.whl"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "13910a5e5dbf7d4ce21c807c801a1f10c261b9a2d538896e93b736c21d7d6b1d"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
  - url: "https://files.pythonhosted.org/packages/db/f0/f9f56675bcb9a3457e41abe3146b98f8e982243518ddb37c3ba48131e79a/nvidia_nvcomp_cu13-5.0.0.6-py3-none-win_amd64.whl"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "6e9990ae4a9bf47bf87946e735076405cd62c2736478adbdfd1292fe9e128cd0"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]

  # Include cudart license because it is statically linked.
  - url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/LICENSE.txt
    fn: cudart_LICENSE.txt
    sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le or not (cuda_compiler_version or "").startswith("1")]
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cf-nvidia-tools 1.*  # [linux]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libnvcomp-dev {{ version.split('.')[:3] | join('.') }}.*
    - pip
    - python
  run:
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
    - python

test:
  imports:
    - nvidia.nvcomp

about:
  home: https://developer.nvidia.com/nvcomp
  license: LicenseRef-nvCOMP-Software-License-Agreement AND LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - cudart_LICENSE.txt
  license_url: https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  summary: "The nvCOMP Python bindings. Developers should install libnvcomp-dev for C-APIs."
  description: |
    The nvCOMP library provides fast lossless data compression and
    decompression using a GPU. It features generic compression interfaces to
    enable developers to use high-performance GPU compressors in their
    applications.

    License Agreements:- The packages are governed by the standard NVIDIA
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA nvCOMP EULA -
    https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  doc_url: https://docs.nvidia.com/cuda/nvcomp/index.html
  dev_url: https://developer.nvidia.com/nvcomp

extra:
  feedstock-name: nvcomp
  recipe-maintainers:
    - conda-forge/cuda
