{% set version = "4.2.0.14" %}

package:
  name: nvcomp
  version: {{ version }}

{% set arm_variant_type = arm_variant_type | default("None") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}

source:
  - url: "https://files.pythonhosted.org/packages/e5/58/371b6df7e9a86921324f1cc780a86c3e47ecbe52f4cc1148efceb4f102cf/nvidia_nvcomp_cu12-4.2.0.14-py3-none-manylinux_2_28_x86_64.whl"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "0d9bc07bf63aeae2e9877d34c8aab6781cf26efa8d2fec05af8b0ec58ca1fd41"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://files.pythonhosted.org/packages/28/ae/21b68910e544ab4476168a9c439f0a008a64c2672136ba619e0723cbd13e/nvidia_nvcomp_cu12-4.2.0.14-py3-none-manylinux_2_28_aarch64.whl"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "bd67b77f7d18daa60757a3400444bf8cc6056dc4d806e22b3a13561f26db692c"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://files.pythonhosted.org/packages/05/76/a9130f0d7ac77e96051a7100900bfcf9f9f98cc3f1954ababdbab568a4ac/nvidia_nvcomp_cu12-4.2.0.14-py3-none-win_amd64.whl"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "c388fc488f640a95eadb035d83da8b4d2d6c2794e1e3088e1bb5abb21242e605"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]

build:
  number: 0
  skip: true  # [osx or ppc64le or not (cuda_compiler_version or "").startswith("1")]
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cf-nvidia-tools 1.*  # [linux]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libnvcomp-dev {{ version.split('.')[:3] | join('.') }}.*
    - pip
    - python
  run:
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
    - python

test:
  imports:
    - nvidia.nvcomp

about:
  home: https://developer.nvidia.com/nvcomp
  license: LicenseRef-nvCOMP-Software-License-Agreement
  license_file: LICENSE
  license_url: https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  summary: "The nvCOMP Python bindings. Developers should install libnvcomp-dev for C-APIs."
  description: |
    The nvCOMP library provides fast lossless data compression and
    decompression using a GPU. It features generic compression interfaces to
    enable developers to use high-performance GPU compressors in their
    applications.

    License Agreements:- The packages are governed by the standard NVIDIA
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA nvCOMP EULA -
    https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  doc_url: https://docs.nvidia.com/cuda/nvcomp/index.html
  dev_url: https://developer.nvidia.com/nvcomp

extra:
  feedstock-name: nvcomp
  recipe-maintainers:
    - conda-forge/cuda
