{% set version = "5.1.0.21" %}

package:
  name: nvcomp
  version: {{ version }}

{% set arm_variant_type = arm_variant_type | default("None") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
source:
  - url: "https://files.pythonhosted.org/packages/ca/9e/1dffa63e4fa6a789e96dc10dde519bb76e4c009feceb1e05b893fa2197b1/nvidia_nvcomp_cu12-5.1.0.21-py3-none-manylinux_2_28_x86_64.whl"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "87b7dbd4c7e00a9f0272467b4023dfd1e57fb778c7593813c636bdfaf1007d69"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://files.pythonhosted.org/packages/19/59/18b6f4aac53942e30bcd81d7ec3e052dce364dbb8e4c6ad7397c854e02c1/nvidia_nvcomp_cu12-5.1.0.21-py3-none-manylinux_2_28_aarch64.whl"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "3ea5a6eba548daebf9dd1d86ee58acfff0fd89cb7c6ee76479cdb07d89cfa871"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://files.pythonhosted.org/packages/13/f3/f2b0aa338968bee12f40ffc7314cd39e094c31f204041b5041264258300f/nvidia_nvcomp_cu12-5.1.0.21-py3-none-win_amd64.whl"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "88dce1acea342a71cdf3ba0e820d6c87a9ac60a3675821554f94634654b2a1e0"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]

  - url: "https://files.pythonhosted.org/packages/08/e9/a60b0df949c65d758420109c5f2c6223caa2ee9c99f0f489641588ce6dbe/nvidia_nvcomp_cu13-5.1.0.21-py3-none-manylinux_2_28_x86_64.whl"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "b8b89f14435529b750f2fab61c35655e234611807e0857d606c77c41807e5d58"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://files.pythonhosted.org/packages/44/93/cadd09eabc687450e0dccecd793d55b3bfd055529a1fb4b05e7bf5767e90/nvidia_nvcomp_cu13-5.1.0.21-py3-none-manylinux_2_28_aarch64.whl"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "e43bdd25ee4265ee5b0e30b2b20b2a88e5249864e1f7a69607a05fc8249152fa"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
  - url: "https://files.pythonhosted.org/packages/ad/68/13952c761f791d0d69a23fe347ca710deda653ee6d54c94bf5521eff1353/nvidia_nvcomp_cu13-5.1.0.21-py3-none-win_amd64.whl"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "6eefb8506a4b279cf1e42f7037dad383d094d8d0089d092acdce94ecfaadafef"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]

  # Include cudart license because it is statically linked.
  - url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/LICENSE.txt
    fn: cudart_LICENSE.txt
    sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le or not (cuda_compiler_version or "").startswith("1")]
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cf-nvidia-tools 1.*  # [linux]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libnvcomp-dev {{ version.split('.')[:3] | join('.') }}.*
    - pip
    - python
  run:
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
    - python

test:
  imports:
    - nvidia.nvcomp

about:
  home: https://developer.nvidia.com/nvcomp
  license: LicenseRef-nvCOMP-Software-License-Agreement AND LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - cudart_LICENSE.txt
  license_url: https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  summary: "The nvCOMP Python bindings. Developers should install libnvcomp-dev for C-APIs."
  description: |
    The nvCOMP library provides fast lossless data compression and
    decompression using a GPU. It features generic compression interfaces to
    enable developers to use high-performance GPU compressors in their
    applications.

    License Agreements:- The packages are governed by the standard NVIDIA
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA nvCOMP EULA -
    https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  doc_url: https://docs.nvidia.com/cuda/nvcomp/index.html
  dev_url: https://developer.nvidia.com/nvcomp

extra:
  feedstock-name: nvcomp
  recipe-maintainers:
    - conda-forge/cuda
