{% set version = "3.0.1" %}
{% set cuda_major = (cuda_compiler_version|default("12.0.0")).split(".")[0] %}
{% set platform = "x86_64" %}  # [linux64]
{% set platform = "SBSA" %}  # [aarch64]
{% set platform = "windows" %}  # [win]
{% set extension = "tgz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: nvcomp
  version: {{ version }}

source:
  - url: https://developer.download.nvidia.com/compute/nvcomp/{{ version }}/local_installers/nvcomp_{{ version }}_{{ platform }}_{{ cuda_major }}.x.{{ extension }}
    sha256: d9d93320b438ce2335d1b1561c213798242f5b6b0f48163c9a96ffa9a08bbb5b  # [linux64 and (cuda_compiler_version or "None").startswith("11")]
    sha256: 739184ab73bdb9e560d8754714f25b8a40b51f08be0d41f77c32da1d21a8eb94  # [linux64 and (cuda_compiler_version or "None").startswith("12")]
    sha256: c1b6cf3f492400ec8594c7b37eb88441121fbbe0de044ff0e29dc7d7d5ff6731  # [aarch64 and (cuda_compiler_version or "None").startswith("11")]
    sha256: f9f801b62df21044e1779aafc6771358cf9b834285d5148bce98a1998daeee8b  # [aarch64 and (cuda_compiler_version or "None").startswith("12")]
    sha256: d773733ab6cba86c365b0d91ce487055d2077c94be78a5121bb798d5fba8a316  # [win and (cuda_compiler_version or "None").startswith("12")]
  # Include cudart license because it is statically linked.
  - url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/LICENSE.txt
    fn: cudart_LICENSE.txt
    sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 2
  skip: True  # [osx or ppc64le or cuda_compiler_version not in ("11.2", "12.0") or (win and cuda_compiler_version.startswith("11"))]
  script:
    - mv -v $SRC_DIR/LICENSE $SRC_DIR/LICENSE.txt  # [linux]
    - mkdir -pv $PREFIX/include                    # [linux]
    - mv -v include/* $PREFIX/include              # [linux]
    - mkdir -pv $PREFIX/lib                        # [linux]
    - mv -v lib/* $PREFIX/lib/                     # [linux]
    - mkdir %LIBRARY_INC%                                   # [win]
    - copy %SRC_DIR%\\include\\* %LIBRARY_INC%\\            # [win]
    - mkdir %LIBRARY_LIB%                                   # [win]
    - copy %SRC_DIR%\\lib\\nvcomp*.lib %LIBRARY_LIB%\\      # [win]
    - mkdir %LIBRARY_BIN%                                   # [win]
    - copy %SRC_DIR%\\lib\\nvcomp*.dll %LIBRARY_BIN%\\      # [win]
  ignore_run_exports_from:
    - {{ compiler('cuda') }}
  run_exports:
    - {{ pin_subpackage("nvcomp") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - sysroot_{{ target_platform }} 2.17  # [linux]
  host:
    - cuda-version {{ cuda_major }}
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - {{ compiler('c') }}  # [linux]
  files:
    - test_load_elf.c      # [linux]
  commands:
    - test -f $PREFIX/include/nvcomp.h                                 # [linux]
    - test -f $PREFIX/include/nvcomp.hpp                               # [linux]
    - test -f $PREFIX/lib/libnvcomp.so                                 # [linux]
    - test -f $PREFIX/lib/libnvcomp_bitcomp.so                         # [linux]
    - test -f $PREFIX/lib/libnvcomp_gdeflate.so                        # [linux]
    - test -f $PREFIX/lib/libnvcomp_gdeflate_cpu.so                    # [linux]
    - ${GCC} test_load_elf.c -std=c99 -Werror -ldl -o test_load_elf    # [linux]
    - for f in $PREFIX/lib/libnvcomp*.so; do ./test_load_elf $f; done  # [linux]
    - if not exist %LIBRARY_INC%/nvcomp.h exit 1                       # [win]
    - if not exist %LIBRARY_INC%/nvcomp.hpp exit 1                     # [win]
    - if not exist %LIBRARY_LIB%/nvcomp.lib exit 1                     # [win]
    - if not exist %LIBRARY_LIB%/nvcomp_bitcomp.lib exit 1             # [win]
    - if not exist %LIBRARY_LIB%/nvcomp_gdeflate.lib exit 1            # [win]
    - if not exist %LIBRARY_BIN%/nvcomp.dll exit 1                     # [win]
    - if not exist %LIBRARY_BIN%/nvcomp_bitcomp.dll exit 1             # [win]
    - if not exist %LIBRARY_BIN%/nvcomp_gdeflate.dll exit 1            # [win]

about:
  home: https://developer.nvidia.com/nvcomp
  license:
    LicenseRef-nvCOMP-Software-License-Agreement AND LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE.txt
    - cudart_LICENSE.txt
  license_url: https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  summary: "High Speed Data Compression Using NVIDIA GPUs"
  description: |
    The nvCOMP library provides fast lossless data compression and
    decompression using a GPU. It features generic compression interfaces to
    enable developers to use high-performance GPU compressors in their
    applications.

    License Agreements:- The packages are governed by the standard NVIDIA
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA nvCOMP EULA -
    https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  doc_url: https://github.com/NVIDIA/nvcomp/blob/main/README.md
  dev_url: https://developer.nvidia.com/nvcomp

extra:
  recipe-maintainers:
    - adibbley
    - bdice
    - jakirkham
