{% set version = "5.2.0.13" %}

package:
  name: nvcomp
  version: {{ version }}

{% set arm_variant_type = arm_variant_type | default("None") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}
source:
  - url: "https://files.pythonhosted.org/packages/e5/75/f9436615f16187d9e6d49c507fb00927d9dfab79ad3daf269a3761fb4c74/nvidia_nvcomp_cu12-{{ version }}-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "c1797b45e041513af8bfc8aad2d727501f15ffbca633a419fd8a8e0ebb7b6a20"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://files.pythonhosted.org/packages/2b/a6/76464cc820f29fc02d21bc22ba369c53fe73ffe9cd62b94adadd5c6803f6/nvidia_nvcomp_cu12-{{ version }}-py3-none-manylinux_2_26_aarch64.whl"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "c67cd3ca1089078078c0002d58f60c5783cd1905db346bea86499918bcb7bb2e"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://files.pythonhosted.org/packages/bb/2a/0d02110d94d9dbf20f15d6a8ffa783b60ed681e4962342ee9d8e31d90de2/nvidia_nvcomp_cu12-{{ version }}-py3-none-win_amd64.whl"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "673894e405f8a3a49790a1fe9de2125fb07a200d47faf8810fdecd4c0577dabe"  # [win and x86_64 and (cuda_compiler_version or "").startswith("12")]

  - url: "https://files.pythonhosted.org/packages/e3/90/7a16ea70a1dc17843713bfc1fd308f9bafd51cacedb54e647aed5eb043c5/nvidia_nvcomp_cu13-{{ version }}-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "73634520491a57eeffa0b2bd0b86686a6e0af51f33099df7be3b5c21697d9f44"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://files.pythonhosted.org/packages/99/61/bf5b63c9902b985acb65af8714b997edf506fc38a25b367d3f6ee613f06a/nvidia_nvcomp_cu13-{{ version }}-py3-none-manylinux_2_26_aarch64.whl"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "a2b3228ab85e327cdc1e400879387b02db45cc28842583c5d5c199a20913eb75"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
  - url: "https://files.pythonhosted.org/packages/82/92/8e9afe459692e5a2724def6f9a17769fb155f872ae3a1f93b97cd9baa4a9/nvidia_nvcomp_cu13-{{ version }}-py3-none-win_amd64.whl"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "7b1553ed8e8c73e3792675e81b130989ebec319006bbdb499bc04a416a5d8834"  # [win and x86_64 and (cuda_compiler_version or "").startswith("13")]

  # Include cudart license because it is statically linked.
  - url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/LICENSE.txt
    fn: cudart_LICENSE.txt
    sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le or not (cuda_compiler_version or "").startswith("1")]
  ignore_run_exports:
    - cuda-version

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cf-nvidia-tools 1.*  # [linux]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - cuda-version {{ cuda_compiler_version }}
    - libnvcomp-dev {{ version.split('.')[:3] | join('.') }}.*
    - pip
    - python
  run:
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
    - python

test:
  imports:
    - nvidia.nvcomp

about:
  home: https://developer.nvidia.com/nvcomp
  license: LicenseRef-nvCOMP-Software-License-Agreement AND LicenseRef-NVIDIA-End-User-License-Agreement
  license_file:
    - LICENSE
    - cudart_LICENSE.txt
  license_url: https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  summary: "The nvCOMP Python bindings. Developers should install libnvcomp-dev for C-APIs."
  description: |
    The nvCOMP library provides fast lossless data compression and
    decompression using a GPU. It features generic compression interfaces to
    enable developers to use high-performance GPU compressors in their
    applications.

    License Agreements:- The packages are governed by the standard NVIDIA
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA nvCOMP EULA -
    https://developer.download.nvidia.com/compute/nvcomp/2.3/LICENSE.txt
  doc_url: https://docs.nvidia.com/cuda/nvcomp/index.html
  dev_url: https://developer.nvidia.com/nvcomp

extra:
  feedstock-name: nvcomp
  recipe-maintainers:
    - conda-forge/cuda
